/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"os"
	"runtime/debug"
	"strconv"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/hertz-contrib/cors"
	"github.com/joho/godotenv"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	"github.com/coze-dev/coze-studio/backend/api/middleware"
	"github.com/coze-dev/coze-studio/backend/api/router"
	"github.com/coze-dev/coze-studio/backend/application"
	"github.com/coze-dev/coze-studio/backend/pkg/lang/conv"
	"github.com/coze-dev/coze-studio/backend/pkg/lang/ternary"
	"github.com/coze-dev/coze-studio/backend/pkg/logs"
	"github.com/coze-dev/coze-studio/backend/types/consts"
)

func main() {
	ctx := context.Background()
	// Please do not change the order of the function calls below
	setCrashOutput()

	if err := loadEnv(); err != nil {
		panic("loadEnv failed, err=" + err.Error())
	}

	setLogLevel()

	// 连接 PostgreSQL 数据库
	db, err := connectPostgreSQL()
	if err != nil {
		panic("Failed to connect PostgreSQL database, err=" + err.Error())
	}

	// 设置存储服务环境变量（必须在 application.Init 之前）
	setupStorageEnvironment()

	if err := application.Init(ctx, db); err != nil {
		panic("InitializeInfra failed, err=" + err.Error())
	}

	startHttpServer()
}

func startHttpServer() {
	maxRequestBodySize := os.Getenv("MAX_REQUEST_BODY_SIZE")
	maxSize := conv.StrToInt64D(maxRequestBodySize, 1024*1024*200)
	addr := getEnv("LISTEN_ADDR", ":8888")

	opts := []config.Option{
		server.WithHostPorts(addr),
		server.WithMaxRequestBodySize(int(maxSize)),
	}

	useSSL := getEnv(consts.UseSSL, "0")
	if useSSL == "1" {
		cert, err := tls.LoadX509KeyPair(getEnv(consts.SSLCertFile, ""),
			getEnv(consts.SSLKeyFile, ""))
		if err != nil {
			fmt.Println(err.Error())
		}
		cfg := &tls.Config{}
		cfg.Certificates = append(cfg.Certificates, cert)
		opts = append(opts, server.WithTLS(cfg))
		logs.Infof("Use SSL")
	}

	s := server.Default(opts...)

	// cors option
	config := cors.DefaultConfig()
	config.AllowAllOrigins = true
	config.AllowHeaders = []string{"*"}
	corsHandler := cors.New(config)

	// Middleware order matters
	s.Use(middleware.ContextCacheMW())     // must be first
	s.Use(middleware.RequestInspectorMW()) // must be second
	s.Use(middleware.SetHostMW())
	s.Use(middleware.SetLogIDMW())
	s.Use(corsHandler)
	s.Use(middleware.AccessLogMW())
	s.Use(middleware.OpenapiAuthMW())
	s.Use(middleware.SessionAuthMW())
	s.Use(middleware.I18nMW()) // must after SessionAuthMW

	router.GeneratedRegister(s)
	s.Spin()
}

func loadEnv() (err error) {
	appEnv := os.Getenv("APP_ENV")
	fileName := ternary.IFElse(appEnv == "", ".env", ".env."+appEnv)

	logs.Infof("load env file: %s", fileName)

	err = godotenv.Load(fileName)
	if err != nil {
		return fmt.Errorf("load env file(%s) failed, err=%w", fileName, err)
	}

	return err
}

func getEnv(key string, defaultValue string) string {
	v := os.Getenv(key)
	if v == "" {
		return defaultValue
	}
	return v
}

func setLogLevel() {
	level := strings.ToLower(os.Getenv("LOG_LEVEL"))

	logs.Infof("log level: %s", level)
	switch level {
	case "trace":
		logs.SetLevel(logs.LevelTrace)
	case "debug":
		logs.SetLevel(logs.LevelDebug)
	case "info":
		logs.SetLevel(logs.LevelInfo)
	case "notice":
		logs.SetLevel(logs.LevelNotice)
	case "warn":
		logs.SetLevel(logs.LevelWarn)
	case "error":
		logs.SetLevel(logs.LevelError)
	case "fatal":
		logs.SetLevel(logs.LevelFatal)
	default:
		logs.SetLevel(logs.LevelInfo)
	}
}

func setCrashOutput() {
	crashFile, _ := os.Create("crash.log")
	debug.SetCrashOutput(crashFile, debug.CrashOptions{})
}

// connectPostgreSQL 连接 PostgreSQL 数据库
func connectPostgreSQL() (*gorm.DB, error) {
	host := getEnv("DATABASE_HOST", "localhost")
	portStr := getEnv("DATABASE_PORT", "15432")
	user := getEnv("DATABASE_USER", "postgres")
	password := getEnv("DATABASE_PASSWORD", "password")
	name := getEnv("DATABASE_NAME", "coze_studio_db")
	sslmode := getEnv("DATABASE_SSLMODE", "disable")
	timezone := getEnv("DATABASE_TIMEZONE", "Asia/Shanghai")

	port, err := strconv.Atoi(portStr)
	if err != nil {
		return nil, fmt.Errorf("invalid database port: %w", err)
	}

	// 构建 DSN
	dsn := fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=%d sslmode=%s TimeZone=%s",
		host, user, password, name, port, sslmode, timezone)

	// 连接数据库
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		return nil, fmt.Errorf("failed to connect database: %w", err)
	}

	// 设置连接池
	sqlDB, err := db.DB()
	if err != nil {
		return nil, fmt.Errorf("failed to get database instance: %w", err)
	}

	maxOpenConnsStr := getEnv("DATABASE_MAX_OPEN_CONNS", "200")
	maxOpenConns, err := strconv.Atoi(maxOpenConnsStr)
	if err != nil {
		maxOpenConns = 200
	}
	maxIdleConnsStr := getEnv("DATABASE_MAX_IDLE_CONNS", "50")
	maxIdleConns, err := strconv.Atoi(maxIdleConnsStr)
	if err != nil {
		maxIdleConns = 50
	}
	connMaxLifetimeStr := getEnv("DATABASE_CONN_MAX_LIFETIME", "600s")
	connMaxLifetime, err := time.ParseDuration(connMaxLifetimeStr)
	if err != nil {
		connMaxLifetime = 600 * time.Second
	}

	sqlDB.SetMaxOpenConns(maxOpenConns)
	sqlDB.SetMaxIdleConns(maxIdleConns)
	sqlDB.SetConnMaxLifetime(connMaxLifetime)

	logs.Infof("PostgreSQL database connected successfully: %s:%d/%s", host, port, name)

	return db, nil
}

// setupStorageEnvironment 从环境变量读取存储配置并设置环境变量
func setupStorageEnvironment() {
	// 从环境变量读取 MinIO 配置
	minioEnabled := getEnv("MINIO_ENABLED", "true")
	if minioEnabled == "true" || minioEnabled == "1" {
		os.Setenv("STORAGE_TYPE", "minio")
		os.Setenv("MINIO_ENDPOINT", getEnv("MINIO_ENDPOINT", "localhost:9000"))
		os.Setenv("MINIO_AK", getEnv("MINIO_ACCESS_KEY", "minioadmin"))
		os.Setenv("MINIO_SK", getEnv("MINIO_SECRET_KEY", "minioadmin"))
		os.Setenv("STORAGE_BUCKET", getEnv("MINIO_BUCKET_NAME", "coze-studio"))
		if getEnv("MINIO_USE_SSL", "false") == "true" || getEnv("MINIO_USE_SSL", "false") == "1" {
			os.Setenv("MINIO_USE_SSL", "true")
		} else {
			os.Setenv("MINIO_USE_SSL", "false")
		}
		logs.Infof("Storage environment variables set for MinIO: %s/%s",
			getEnv("MINIO_ENDPOINT", "localhost:9000"),
			getEnv("MINIO_BUCKET_NAME", "coze-studio"))
	} else {
		logs.Warnf("MinIO is not enabled, storage type may not be set")
	}
}
